### ISSUE TITLE
No info in image

### ISSUE THREAD

**Issue by Samcfuchs** [JacisNonsense/TravisCards#1]
When I go to the image for our repo, I get this image, with only the title of the repo, and no info on the build.

![image](https://cloud.githubusercontent.com/assets/6753408/12867529/de24d7b8-ccbd-11e5-9011-4c96c64f8448.png)

**Comment by JaciBrunning** [comment]
Your .travis.yml file needs some extra details in it: 
https://github.com/JacisNonsense/TravisCards#how  

After committing the changes to the travis.yml file, the next build should generate a proper card

**Comment by Samcfuchs** [comment]
My bad. Thanks!
